config/routes.rb
Prwatch::Application.routes.draw do
  mount Afterparty::Engine, at: "afterparty", as: "afterparty_engine"
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  regex = /[\w|\.*|-]+/
  constraints = {repository: regex, owner: regex}
  get 'github/:owner/:repository' => 'repositories#show',
    as: "repository",
    constraints: constraints
  put 'github/:owner/:repository' => 'repositories#refresh',
    constraints: constraints
  get 'github/:owner/:repository/badge/:variant' => 'repositories#badge',
    as: 'badge',
    constraints: constraints

  get 'analysis' => "repositories#analysis", as: :analysis

  root "repositories#index"

end

app/views/layouts/_ad.html.haml
- if Date.today < Date.new(2014, 11)
  .row
    .col-md-12.text-center.well-highlight.well
      %p Want to learn how to make charts & graphs like the ones you see here?
      The creator of Issue Stats is
      = link_to "crowdfunding a course", "https://www.uludum.org/funds/6"
      about building interactive data visualizations.

app/views/layouts/_welcome.html.haml
- key = "has_seen_welcome_v2"
- unless cookies[key]
  #welcome-alert.alert.alert-info.text-center
    %button.close{"data-dismiss" => "alert", type: "button"}
      %span{"aria-hidden" => "true"} ×
      %span.sr-only Close
    %h3
      Welcome to
      = succeed "!" do
        %strong Issue Stats
    %br
    %p.lead
      Analyze and compare how long it takes for
      = link_to "Github", "https://github.com", target: "_blank", class: "plain-link"
      issues to be closed.
    %br
    %br
    %p Check out some examples:
    %br
    %br
    .row
      - ["rails/rails", "nodejs/node", "twbs/bootstrap"].each do |github_key|
        - split = github_key.split("/")
        - opts = {owner: split[0], repository: split[1]}
        .col-lg-4
          %p.lead
            = link_to github_key, repository_path(opts)
          %br
          = image_tag badge_url(opts.merge(variant: "pr", style: "flat"))
          %br
          %br
          = image_tag badge_url(opts.merge(variant: "issue", style: "flat"))
    %br
    %br
  :coffeescript
    @welcomeMessageKey = "#{key}"

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      - if content_for? :title
        = yield(:title)
        = " - "
      Issue Stats
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Lato:300,400,700", "application"
    = javascript_include_tag "application"
    = csrf_meta_tag
    = favicon_link_tag
    = yield(:head)
    = analytics_init if Rails.env.production?

  %body
    .navbar.navbar-default{role: "navigation"}
      .container
        .navbar-header
          %a.na
          %a.navbar-brand{href: "/"}
            = fa_icon("bar-chart-o")
            Issue Stats
        %form#search.navbar-form.navbar-right{:role => "search"}
          .form-group.input-group
            .input-group-addon github.com/
            %input#search-input.form-control{:placeholder => ":owner/:repository", :type => "text"}
          %button.btn.btn-default{:type => "submit"} Submit
    = render partial: "layouts/welcome"
    .container
      = yield
    %br
    %hr
    %footer.footer.text-center
      = render partial: "layouts/ad"
      %p.small
        Looking for more
        = succeed "?" do
          = link_to "interesting graphs and analysis", analysis_path

      Built by
      = link_to "Hank Stoever", "http://hankstoever.com", target: "_blank", class: "plain-link-underlined"
      = link_to fa_icon(:github), "https://github.com/hstove/issue_stats"
      = link_to fa_icon(:twitter), "https://twitter.com/heynky"
    %br